// This file was auto-generated by Fern from our API Definition.

export const DetectantApiEnvironment = {
    Default: "",
} as const;

export type DetectantApiEnvironment = typeof DetectantApiEnvironment.Default;
