// This file was auto-generated by Fern from our API Definition.

export interface ApiError {
    /** Stable machine-readable error code. */
    code: string;
    /** Human-readable error message. */
    message: string;
    /** Context such as the ID of a failed stored scan. Empty when no context applies. */
    details: Record<string, string>;
}
