// This file was auto-generated by Fern from our API Definition.

export interface HealthResponse {
    status: HealthResponse.Status;
}

export namespace HealthResponse {
    export const Status = {
        Ok: "ok",
        Degraded: "degraded",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
