// This file was auto-generated by Fern from our API Definition.

import type * as DetectantApi from "../index.js";

export interface ScanList {
    /** Scan records. Empty when the account has no scans. */
    items: DetectantApi.Scan[];
    /** Opaque cursor for the next page, or `null` when no next page exists. */
    next_cursor: string | null;
}
