// This file was auto-generated by Fern from our API Definition.

import type * as DetectantApi from "../index.js";

export interface ScanBatchResult {
    /** Zero-based position of the submitted file. */
    index: number;
    /** Filename supplied by the multipart part. */
    filename: string;
    /** HTTP status that the equivalent single-file request would return. */
    http_status: number;
    /** Stored scan result, including its scan ID, or null when validation failed before a scan was created. */
    scan: DetectantApi.Scan | null;
    /** Per-file validation or scanning error, or null when the scan completed. */
    error: DetectantApi.ApiError | null;
}
