// This file was auto-generated by Fern from our API Definition.

import type * as DetectantApi from "../index.js";

export interface ScanBatchResponse {
    /** One outcome per submitted file, in submission order. */
    results: DetectantApi.ScanBatchResult[];
}
