// This file was auto-generated by Fern from our API Definition.

import type * as DetectantApi from "../index.js";

export interface Scan {
    /** Server-generated scan identifier. */
    id: string;
    created_at: string;
    status: Scan.Status;
    verdict: Scan.Verdict;
    /** Filename supplied by the multipart upload. */
    filename: string;
    sha256: string;
    size_bytes: number;
    duration_ms: number;
    /** Failure information, or `null` when the scan completed. */
    failure: DetectantApi.ScanFailure | null;
    /** Detection names reported for the file. Empty when no threats were detected. */
    detections: string[];
    type_analysis: DetectantApi.TypeAnalysis;
}

export namespace Scan {
    export const Status = {
        Completed: "completed",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const Verdict = {
        Clean: "clean",
        Malicious: "malicious",
        Suspicious: "suspicious",
        Unknown: "unknown",
    } as const;
    export type Verdict = (typeof Verdict)[keyof typeof Verdict];
}
