// This file was auto-generated by Fern from our API Definition.

import type * as DetectantApi from "../index.js";

export interface TypeAnalysis {
    declared: DetectantApi.TypeDeclaration;
    identified: DetectantApi.TypeIdentification;
    status: TypeAnalysis.Status;
    structurally_valid: boolean | null;
    confidence: TypeAnalysis.Confidence;
    reason: DetectantApi.TypeAnalysisReason | null;
}

export namespace TypeAnalysis {
    export const Status = {
        Match: "match",
        Compatible: "compatible",
        Mismatch: "mismatch",
        Malformed: "malformed",
        Unscannable: "unscannable",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const Confidence = {
        High: "high",
        Medium: "medium",
        Low: "low",
    } as const;
    export type Confidence = (typeof Confidence)[keyof typeof Confidence];
}
