// This file was auto-generated by Fern from our API Definition.

export interface TypeDeclaration {
    /** Raw extension from the uploaded filename, without the leading dot. */
    extension?: string | undefined;
    /** Normalized MIME type declared by the multipart part. */
    mime?: string | undefined;
}
