// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         scan_id: "scan_0123456789abcdef0123456789abcdef"
 *     }
 */
export interface GetScanRequest {
    /** Scan identifier returned by `createScan` or `listScans`. */
    scan_id: string;
}
