// This file was auto-generated by Fern from our API Definition.

export interface ScanFailure {
    code: ScanFailure.Code;
    message: string;
}

export namespace ScanFailure {
    export const Code = {
        ScannerUnavailable: "SCANNER_UNAVAILABLE",
        ContentExpansionLimitExceeded: "CONTENT_EXPANSION_LIMIT_EXCEEDED",
    } as const;
    export type Code = (typeof Code)[keyof typeof Code];
}
