// This file was auto-generated by Fern from our API Definition.

export interface ScanSource {
    type: ScanSource.Type;
    /** S3 integration identifier, or `null` for direct API scans. */
    integration_id: string | null;
    /** S3 integration name, or `null` for direct API scans. */
    integration_name: string | null;
}

export namespace ScanSource {
    export const Type = {
        Api: "api",
        S3: "s3",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
