// This file was auto-generated by Fern from our API Definition.

export interface TypeAnalysisReason {
    code: TypeAnalysisReason.Code;
    claimed?: string | undefined;
    detected?: string | undefined;
}

export namespace TypeAnalysisReason {
    export const Code = {
        MalformedFile: "malformed_file",
        EncryptedArchive: "encrypted_archive",
        UnsupportedArchive: "unsupported_archive",
        ContentExpansionLimitExceeded: "content_expansion_limit_exceeded",
        FileTypeMismatch: "file_type_mismatch",
    } as const;
    export type Code = (typeof Code)[keyof typeof Code];
}
