// This file was auto-generated by Fern from our API Definition.

export interface TypeIdentification {
    /** Canonical format identified from file content. */
    format?: string | undefined;
    /** Canonical MIME type identified from file content. */
    mime?: string | undefined;
}
