// This file was auto-generated by Fern from our API Definition.

import type * as DetectantApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListScansRequest {
    /** Maximum results to return. Values above 200 are capped at 200; omission uses 50. */
    limit?: number;
    /** Opaque cursor returned as `next_cursor` by a previous request. */
    cursor?: string;
    /** Case-sensitive PostgreSQL `LIKE` fragment matched against the stored verdict; `%` and `_` act as wildcards. */
    verdict?: string;
    /** Case-insensitive fragment matched against the scan identifier. */
    scan_id?: string;
    /** Return direct API scans or scans submitted by an S3 integration. */
    source_type?: DetectantApi.ListScansRequestSourceType;
    /** Return scans submitted by this S3 integration. */
    storage_integration_id?: string;
    /** Return scans by failure presence or customer-facing failure code. */
    failure?: DetectantApi.ListScansRequestFailure;
    /** Case-sensitive PostgreSQL `LIKE` fragment matched against the stored filename; `%` and `_` act as wildcards. */
    filename?: string;
    /** Case-sensitive PostgreSQL `LIKE` fragment matched against the stored engine signature; `%` and `_` act as wildcards. */
    engine_signature?: string;
    /** Case-sensitive PostgreSQL `LIKE` fragment matched against stored detection rules; `%` and `_` act as wildcards. */
    detection_rule?: string;
}
