// This file was auto-generated by Fern from our API Definition.

export const ListScansRequestFailure = {
    Any: "any",
    None: "none",
    ScannerUnavailable: "SCANNER_UNAVAILABLE",
    ContentExpansionLimitExceeded: "CONTENT_EXPANSION_LIMIT_EXCEEDED",
} as const;
export type ListScansRequestFailure = (typeof ListScansRequestFailure)[keyof typeof ListScansRequestFailure];
