// This file was auto-generated by Fern from our API Definition.

export const ListScansRequestSourceType = {
    Api: "api",
    S3: "s3",
} as const;
export type ListScansRequestSourceType = (typeof ListScansRequestSourceType)[keyof typeof ListScansRequestSourceType];
