// This file was auto-generated by Fern from our API Definition.

import * as DetectantApi from "../../src/api/index";
import { Detectant } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("HealthClient", () => {
    test("getLiveness", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "ok" };

        server.mockEndpoint().get("/health/live").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.health.getLiveness();
        expect(response).toEqual(rawResponseBody);
    });

    test("getReadiness (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "ok" };

        server.mockEndpoint().get("/health/ready").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.health.getReadiness();
        expect(response).toEqual(rawResponseBody);
    });

    test("getReadiness (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/health/ready").respondWith().statusCode(503).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.health.getReadiness();
        }).rejects.toThrow(DetectantApi.ServiceUnavailableError);
    });
});
