// This file was auto-generated by Fern from our API Definition.

import * as DetectantApi from "../../src/api/index";
import { Detectant } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ScansClient", () => {
    test("listScans (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "scan_0123456789abcdef0123456789abcdef",
                    created_at: "2024-01-15T09:30:00Z",
                    status: "completed",
                    verdict: "clean",
                    filename: "filename",
                    sha256: "sha256",
                    size_bytes: 1000000,
                    duration_ms: 1.1,
                    failure: { code: "SCANNER_UNAVAILABLE", message: "message" },
                    detections: ["detections"],
                    type_analysis: {
                        declared: {},
                        identified: {},
                        status: "match",
                        structurally_valid: null,
                        confidence: "high",
                        reason: null,
                    },
                },
            ],
            next_cursor: "next_cursor",
        };

        server.mockEndpoint().get("/v1/scans").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.scans.listScans();
        expect(response).toEqual(rawResponseBody);
    });

    test("listScans (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", details: { details: "details" } } };

        server.mockEndpoint().get("/v1/scans").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.scans.listScans();
        }).rejects.toThrow(DetectantApi.BadRequestError);
    });

    test("listScans (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", details: { details: "details" } } };

        server.mockEndpoint().get("/v1/scans").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.scans.listScans();
        }).rejects.toThrow(DetectantApi.UnauthorizedError);
    });

    test("listScans (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", details: { details: "details" } } };

        server.mockEndpoint().get("/v1/scans").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.scans.listScans();
        }).rejects.toThrow(DetectantApi.TooManyRequestsError);
    });

    test("listScans (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", details: { details: "details" } } };

        server.mockEndpoint().get("/v1/scans").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.scans.listScans();
        }).rejects.toThrow(DetectantApi.InternalServerError);
    });

    test("getScan (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "scan_0123456789abcdef0123456789abcdef",
            created_at: "2024-01-15T09:30:00Z",
            status: "completed",
            verdict: "clean",
            filename: "filename",
            sha256: "sha256",
            size_bytes: 1000000,
            duration_ms: 1.1,
            failure: { code: "SCANNER_UNAVAILABLE", message: "message" },
            detections: ["detections"],
            type_analysis: {
                declared: { extension: "extension", mime: "mime" },
                identified: { format: "format", mime: "mime" },
                status: "match",
                structurally_valid: true,
                confidence: "high",
                reason: { code: "malformed_file", claimed: "claimed", detected: "detected" },
            },
        };

        server
            .mockEndpoint()
            .get("/v1/scans/scan_0123456789abcdef0123456789abcdef")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.scans.getScan({
            scan_id: "scan_0123456789abcdef0123456789abcdef",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getScan (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", details: { details: "details" } } };

        server.mockEndpoint().get("/v1/scans/scan_id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.scans.getScan({
                scan_id: "scan_id",
            });
        }).rejects.toThrow(DetectantApi.UnauthorizedError);
    });

    test("getScan (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", details: { details: "details" } } };

        server.mockEndpoint().get("/v1/scans/scan_id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.scans.getScan({
                scan_id: "scan_id",
            });
        }).rejects.toThrow(DetectantApi.NotFoundError);
    });

    test("getScan (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", details: { details: "details" } } };

        server.mockEndpoint().get("/v1/scans/scan_id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.scans.getScan({
                scan_id: "scan_id",
            });
        }).rejects.toThrow(DetectantApi.TooManyRequestsError);
    });

    test("getScan (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Detectant({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", details: { details: "details" } } };

        server.mockEndpoint().get("/v1/scans/scan_id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.scans.getScan({
                scan_id: "scan_id",
            });
        }).rejects.toThrow(DetectantApi.InternalServerError);
    });
});
