// This file was auto-generated by Fern from our API Definition.

export const DetectantApiEnvironment = {
    Default: "https://api.detectant.com",
} as const;

export type DetectantApiEnvironment = typeof DetectantApiEnvironment.Default;
